### ISSUE TITLE
ENOENT: no such file or directory, open 'crypto'

### ISSUE THREAD

**Issue by OllieJT** [draftbit/twitter-lite#104]
I'm trying to use twitter-lite in a [Sapper](https://github.com/sveltejs/sapper) app, compiled with [Rollup](https://github.com/rollup/rollup).

I'm not sure if this is an issue from Rollup or twitter-lite. All I can find from googling is archived issues from ~2018. I'd appreciate some help or a nudge in the right direction.

Error

```
✗ client

Couldbashnot load crypto (imported by /PATH__TO__PROJECT/node_modules/twitter-lite/dist/twitter.m.js): ENOENT: no such file or directory, open 'crypto'

✔ server (3.2s)

✔ service worker (53ms)
```

**Comment by ciffelia** [comment]
It seems that this library can be used on Node.js only, because `crypto` module is a native module of Node.js. I will fix README soon.
