### ISSUE TITLE
App Auth doesn't work

### ISSUE THREAD

**Issue by DarthPresident** [draftbit/twitter-lite#107]
I am trying to use this code, but in result i receive Not Authorized. I have created an app in my developer account, but can't use app auth.

`cvar Twitter = require('twitter-lite');
     
     async function foo() {
     var user = new Twitter({
        consumer_key: 'key',
        consumer_secret: 'secret'
    });

    const response = await user.getBearerToken();
    const app = new Twitter({
        bearer_token: response.access_token
    });
    await user.get("statuses/user_timeline").catch(e => console.log(e));
    }
`

**Comment by GeoffreyPlitt** [comment]
You need to add access_token and access_secret from the Twitter app portal to your constructor params. Works for me.
