### ISSUE TITLE
[help wanted] Stream tweets matching keywords/hashtags + only from certain users

### ISSUE THREAD

**Issue by kieronbos** [draftbit/twitter-lite#108]
Hello, sorry first of all to create an issue for help.

Is this library capable of performing a stream function, that only matches against tweets made with certain hashtags/keywords, but also only from certain authors, for example like this which works on twitter.com: 

`(dragon OR #tesla OR microsoft)(from:elonmusk OR from:billgates)`

Or, in URL form: https://twitter.com/search?q=%60(dragon%20OR%20%23tesla%20OR%20microsoft)(from%3Aelonmusk%20OR%20from%3Abillgates)%60&src=typed_query&f=live

Thank you

Edit: Sub question, could you also stream the tweets made by accounts that a 'slave' account follows? To alleviate the need to maintain a list, you could simply follow someone, and their tweets would be streamed.

**Comment by dandv** [comment]
Hi, no worries, questions are welcome.

The library simply transmits request to the Twitter API, and our goal is to make it support whatever Twitter's API supports.

Your first use case can be achieved via [streaming](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter). You'd set the `track` and `follow` parameters.

For the second use case, you can [get the account's friends](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-list) and pass that list of IDs as the `follow` parameter to the streaming API above.

Does that help?

**Comment by kieronbos** [comment]
It does! Do you have any examples of getting the accounts friends? 

Thats the way i think i will go, then like you say pass that into the follow!

**Comment by kieronbos** [comment]
I have this small example, ```const response = client.get("friends/list", {
      id: "id_here"
    });
    console.log(response)```

but it just returns `Promise { <pending> }`

**Comment by kieronbos** [comment]
Ah, I have it returning now, it doesnt seem to only return a list of ID's though, any tips on how to do that?

Currently it seems to get the friends' first tweets?

Thanks!

**Comment by kieronbos** [comment]
Thank you for the edit, I was going for that but couldn't get it to play ball haha!

Right I've discovered the friends/IDs now, but I'm still seeing those results are paginated in a sense, so could you programmatically cycle through those pages, and then have them all in a single, say 500 entry array?

Or, am I doing it wrong and it should be printing them out as a single array with them all in?

Thanks!

**Comment by dandv** [comment]
[friends/ids](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-ids) already returns 5000 IDs per response, but if you want to [paginate](https://developer.twitter.com/en/docs/ads/general/guides/pagination), you can do something like this:

```js
let cursor = -1;
const ids = new Set();
do {
  const response = await twitter.get('friends/ids', { id });
  // In case the API duplicates the last ID into the next page, or if
  // there are potential consistency problems, we'll a Set.
  for (const id of response.ids)
    ids.add(id);
  cursor = response.next_cursor_str;
} while (Number(cursor) !== 0);
```

@peterpme, @dylanirlbeck et. al. - should we we offering a method to paginate cursored results?

**Comment by kieronbos** [comment]
Oh! Sorry, this its probably me making it confusing, I **don't** want pagination, I want all them ID's up to 5k in one simple array, so I can chuck them in as the source of my stream.

Right now I'm seeing that I get approx 100 in the response, then it says `... 49 More Items` like so:
<img width="468" alt="Capture" src="https://user-images.githubusercontent.com/8655212/84366515-d85df080-abca-11ea-961d-0479611caa90.PNG">

But are you saying, they're still 'there' and I could just take that `response.ids` array, and toss it into a stream command?

Thanks very much so far!

**Comment by dandv** [comment]
Well, how many IDs are there in total? I'd guess 149, and you can check that in Twitter's UI.

"49 more items" is just how `console.log` displays arrays. Try `console.log(ids.slice(100)` to see array items #100 through the end, or better yet, use an IDE that lets you step through the code and inspect all array elements.

So yep, you can pass that array to other commands.

**Comment by kieronbos** [comment]
Thanks that's great! That just about covers this one haha! I really appreciate the help!

I'll look for something to run with other than my Terminal!
