### ISSUE TITLE
Switch to Crypto-js dependency

### ISSUE THREAD

**Issue by mprovost-webcreek** [draftbit/twitter-lite#110]
I am currently developing an app that uses Ionic with Cordova and Angular. I am trying to add a simple Twitter login option. The issue is that the `crypto` module is only available in Node, and not in Ionic. If this project used [`Crypto-js`](https://www.npmjs.com/package/crypto-js) rather than `crypto`, I would be able to continue my development. I would be willing to implement this quick fix, but I wanted to check with the maintainers before I started changing things.

**Comment by giacomocerquone** [comment]
Plus I'd say that this should be the default since in the readme we can see written that it's both compatible with node and in the browser

**Comment by giacomocerquone** [comment]
done @mprovost-webcreek

https://www.npmjs.com/package/twitter-lite-older-crypto/v/0.15.4
https://github.com/giacomocerquone/twitter-lite-older-crypto

I don't think I want to merge that here, it's considered unsafe and it uses packages that will not receive updates.
Still, it might be useful to someone.

consider this @dandv @peterpme
