### ISSUE TITLE
Any way to specify multiple languages for Streams?

### ISSUE THREAD

**Issue by jxlarrea** [draftbit/twitter-lite#120]
I see documentation for track, locations and follow but no languages whatsoever. The parameter is supported according to the documentation on Twitter: https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters

**Comment by kevin-shelaga** [comment]
var client = getTwitterClient();
          const stream = client.stream("statuses/filter", {
            follow: follows[0].toString(),
            language: ["en", "fr"],
          });
