### ISSUE TITLE
Id overflow in 'followers/ids' Endpoint

### ISSUE THREAD

**Issue by amiralitaheri** [draftbit/twitter-lite#122]
Converting response to json in `_handleResponse` function causes overflow, and Ids become invalid. 
Correct json 
```json
{
    "ids": [
        6666286963965050880,
        666355086822674434,
    ],
    "next_cursor": 0,
    "next_cursor_str": "0",
    "previous_cursor": 0,
    "previous_cursor_str": "0",
    "total_count": null
}
```
Wrong json
```json
{
    "ids": [
        6666286963965051000,
        666355086822674400,
    ],
    "next_cursor": 0,
    "next_cursor_str": "0",
    "previous_cursor": 0,
    "previous_cursor_str": "0",
    "total_count": null
}
```

**Comment by dandv** [comment]
Have you read the README section about [numeric vs string IDs](https://github.com/draftbit/twitter-lite#numeric-vs-string-ids)?

If you can still reproduce the problem, please add a test case like [this](https://github.com/draftbit/twitter-lite/blob/master/test/twitter.test.js#L334-L352).

**Comment by amiralitaheri** [comment]
@dandv  
Sorry I didn't saw that, but isn't it better to add  `stringify_ids: true` by default? since numeric ids are useless.
