### ISSUE TITLE
Retry on timeout?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [draftbit/twitter-lite#123]
Is there a way to automatically retry when there's a timeout?

**Comment by dandv** [comment]
No, but the logic is pretty simple - you want to retry up to MAX_RETRIES times in case of certain types of errors, and [sleep](https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep/39914235#39914235) in between retries:

```js
for (let i = 0; i < MAX_RETRIES; i++) {
  try {
    const result = await twitter.method(...);
    break;  // success; exit the retry loop
  } catch (error) {
    console.warn(`Twitter API error try ${i} / ${twitter.RETRIES}:`, error);
    // can also look at the error code here, and abort on unrecoverable errors
  }
  await sleep(SLEEP_BETWEEN_RETRIES);
}
```

**Comment by plu5** [comment]
Except an error will not be thrown if the server stops responding as you don’t support specifying a timeout in the first place, see https://github.com/draftbit/twitter-lite/issues/114
