### ISSUE TITLE
Cannot find name 'Response'.

### ISSUE THREAD

**Issue by pleshevskiy** [draftbit/twitter-lite#135]
I have error when build application via `tsc`.

`node_modules/twitter-lite/index.d.ts:48:44 - error TS2304: Cannot find name 'Response'.`

```typescript
private static _handleResponse(response: Response): Promise<object>;
```

In index.d.ts, Response type is not declared.

**Comment by transitive-bullshit** [comment]
You need to add `"dom"` to your tsconfig's `compilerOptions.lib` array.
