### ISSUE TITLE
Twitter API v2 Support

### ISSUE THREAD

**Issue by bna-ch** [draftbit/twitter-lite#136]
Hi, is there any planned support for the v2 API's that just got released?

**Comment by peterpme** [comment]
Hey @bna-ch if you have any insight, we would absolutely love your help!

**Comment by kevin-shelaga** [comment]
https://blog.twitter.com/developer/en_us/topics/tools/2020/introducing_new_twitter_api.html

**Comment by piquet-h** [comment]
@peterpme, would it be reasonable to add a version parameter to get() such that
get(version, resource, headers). Pass that parameter through to _makeRequest('GET', version, resource, parameters), which then uses getUrl instead of this.url to construct the url endpoint. 

The only difference that I can see in the api is the endpoint. It changes from /1.1/resource to /2/resource

I'm happy to submit the pull request if you're good with the change.

Pete

**Comment by peterpme** [comment]
@piquet-h Great idea, go for it!

**Comment by Santiago8888** [comment]
For anyone looking for a quick hack, this got it working for me:

```
diff --git a/twitter.js b/twitter.js
index 273a647..3d54cfa 100644
--- a/twitter.js
+++ b/twitter.js
@@ -201,7 +201,7 @@ class Twitter {
    */
   _makeRequest(method, resource, parameters) {
     const requestData = {
-      url: `${this.url}/${resource}.json`,
+      url: `${this.url}/${resource}${this.url.includes('2') ? '' : '.json'}`,
       method,
     };
     if (parameters)
```

**Comment by piquet-h** [comment]
There's a pull request waiting to be merged.

**Comment by Santiago8888** [comment]
Thanks @piquet-h, for reference it's #144 
It was proposed one month ago, anything we can do to push it forward?

**Comment by Santiago8888** [comment]
Update: the PR was merged but the package was last published about six months ago.

**Comment by connorzg** [comment]
@peterpme I'm not sure who currently does the publishing but could this package get updated on npm please? I'm already using this package for a lot of other endpoints so would like to be able to fit in the V2 implementation using your same library

**Comment by AmichayMiara** [comment]
@peterpme 
You can install the current code with this link
npm i https://github.com/draftbit/twitter-lite.git

**Comment by AmichayMiara** [comment]
> 
> 
> @peterpme I'm not sure who currently does the publishing but could this package get updated on npm please? I'm already using this package for a lot of other endpoints so would like to be able to fit in the V2 implementation using your same library


You can install the current code directly with this link
npm i https://github.com/draftbit/twitter-lite.git

**Comment by peterpme** [comment]
Sorry everyone I will try to publish a new version today. It is hard to maintain a library I don't regularly use so I would love a hand if anyone is interested :)

**Comment by connorzg** [comment]
@peterpme thank you! I know a few people have voiced their desire to help maintain in #150 I'd be interested as well! Maybe we can continue the conversation there on how to involve others and reduce the burden on you a bit?

**Comment by rlueder** [comment]
Taken care of on #144
