### ISSUE TITLE
Streaming data doesn't show any tweets until 4 seconds afterwards?

### ISSUE THREAD

**Issue by napindc** [draftbit/twitter-lite#142]
I'm using the example from the docs to stream data, but for the parameters I'm only setting "follow" to a single ID (one of my twitter accounts).

After tweeting from the account, I consistently see it is around 4 seconds until the `on("data", tweet => console.log("data"))` triggers. Is there anyway I can get this to return data faster than 4 seconds?

**Comment by T0TProduction** [comment]
Just so I understand correctly, its 4 seconds from posting->your code logs it?

I'm pretty sure that's a combination of bottlenecks across the board, from twitters side.
You can't access the data any earlier from the code, so afaik nothing you can do.

Out of curiosity, why does it need to be faster than 4 seconds?

**Comment by napindc** [comment]
Yes it is 4 seconds from posting to logs.

I’d like it to be faster as I am trying to do things with stocks with it - and stocks you need to be 1-2 seconds after a tweet sometimes before the world reacts and brings the price up

**Comment by T0TProduction** [comment]
well if it's about stocks I wouldn't rely on twitter anyways...

either way, as far as I know, you can't change anything about the speed as it's a simple stream coming directly from twitters API.
