### ISSUE TITLE
some tweets do not give entities.media while they have media images

### ISSUE THREAD

**Issue by k2helix** [draftbit/twitter-lite#145]
Hello, I'm using twitter-lite to get tweets, but sometimes when I get a tweet (like the tweet with id 1311296614942650369), it doesn't display the media correctly. I'm using
`client.get('statuses/show', { id: '1311296614942650369' }, function(err, data, response) {
  console.log(data)
})`

**Comment by Mo9a7i** [comment]
That might be a twitter related issue.
I have been facing a similar problem, browsing my liked tweets and unliking them, reaches to a point where the API does not give anymore tweets, while twitter has them clear.

**Comment by Mo9a7i** [comment]
> Hello, I'm using twitter-lite to get tweets, but sometimes when I get a tweet (like the tweet with id 1311296614942650369), it doesn't display the media correctly. I'm using
> 
> `client.get('statuses/show', { id: '1311296614942650369' }, function(err, data, response) {
> 
>   console.log(data)
> 
> })`

By the way,

Try adding this after id

`tweet_mode: extended`

**Comment by ciffelia** [comment]
I found a similar question on StackOverflow: https://stackoverflow.com/questions/39709511/twitter-api-not-returning-images
As Mo9a7i suggested, please use `tweet_mode: 'extended'`.
