### ISSUE TITLE
Is it possible to edit a stream?

### ISSUE THREAD

**Issue by zever55** [draftbit/twitter-lite#149]
I create a stream like this:
```javascript
accounts = [1, 2, 3] // some user ids

stream = client.stream("statuses/filter", { follow: accounts.join(',') })
	.on("start", response => console.log("start"))
	.on("data", tweet => console.log("data", tweet.text))
	.on("ping", () => console.log("ping"))
	.on("error", error => console.log("error", error))
	.on("end", response => console.log("end"));
```

While the program is running I sometimes change the accounts list so my question is: can you edit a running stream or do you have to destroy the current one and start a new one or is there another method? Any help will be appreciated.

**Comment by abmusse** [comment]
I have the same question. I think the only way to is to destroy and start another stream but this can lead to `420 Enhance your calm` stated in the [README](https://github.com/draftbit/twitter-lite#streams). I'm currently experimenting to find out how long I should wait before recreating stream to avoid that `420` error code.

**Comment by abmusse** [comment]
Maybe we could use https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/introduction instead. Would be nice if there was example using this API.

**Comment by ciffelia** [comment]
According to [statuses/filter reference](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/api-reference/post-statuses-filter) it seems to be impossible to edit a stream.
As abmusse mentioned, you may use new [filtered stream API](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/introduction) which allows you to add or delete rules after creating a stream.
