### ISSUE TITLE
Clarify how to pass POST parameters

### ISSUE THREAD

**Issue by gnomeontherun** [draftbit/twitter-lite#15]
I cannot favorite something because the URL has to be as defined here https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-favorites-create

`POST https://api.twitter.com/1.1/favorites/create.json?id=243138128959913986`

The URL is only constructed by the resource, and doesn't support params https://github.com/Preposterous/twitter-lite/blob/master/twitter.js#L81

**Comment by peterpme** [comment]
Hey @gnomeontherun post parameters are supported in 0.4.0

Thanks so much for letting me know!

**Comment by dandv** [comment]
I've found it counter-intuitive to pass a `null` body, *then* my actual parameters to [client.post](https://github.com/Preposterous/twitter-lite/blob/master/twitter.js#L133):

```
await client.post("friendships/create", null, {
    screen_name: 'dandv'
  });
```

This also breaks drop-in compatibility with twit.

Is the `body` parameter reserved for certain things, like uploading media? If so, there should be a note in the README about this. In [its README, twit](https://github.com/ttezel/twit) doesn't seem to ever use any other parameters than `parameters`.

CC @tylerbuchea
