### ISSUE TITLE
Anyone want to help maintain this project? Would love your help!

### ISSUE THREAD

**Issue by peterpme** [draftbit/twitter-lite#150]
Hey everyone, looking for help maintaining this! Please leave a comment here if you're interested.

**Comment by ciffelia** [comment]
Hi, I'm using this library in my hobby project and would like to help maintain this. How can I help?

**Comment by Santiago8888** [comment]
I'm also using it, and might be interested in helping.

**Comment by peterpme** [comment]
If either @ciffelia or @Santiago8888 are strongly interested in helping, more than happy to give you access :)

**Comment by ciffelia** [comment]
@peterpme I'd love to get access to merge PRs and push some improvements 🚀

**Comment by peterpme** [comment]
Just published 1.1.0 everyone

**Comment by Fdebijl** [comment]
@peterpme I would love to keep helping out with the typings and reviewing pr's/triaging issues

**Comment by JayHelton** [comment]
Hi! I'd be interested in helping contribute and maintain this library.

**Comment by JayHelton** [comment]
> Hi! I'd be interested in helping contribute and maintain this library.

Feel free to email me at the email in my profile if you need anything specific. In the meantime I'll be subscribing to the repos alerts and will look back on open issues.

**Comment by creativecreatorormaybenot** [comment]
If anyone wants to help out and is looking for an issue to hack on, I think https://github.com/draftbit/twitter-lite/issues/156 could be interesting, maybe trivial.

I would love to help, but I do not have enough Node experience to assist effectively right now.

**Comment by rlueder** [comment]
@peterpme hey there, I have a small open source project called [TidyTweets](https://github.com/rlueder/tidytweets) that relies heavily on `twitter-lite`.

I'd be willing to help sort through open issues at first and start submitting PRs as needed. Let me know if you're still looking for help maintaining. Thanks!

**Comment by peterpme** [comment]
@rlueder done, sorry for the delay!

@ciffelia and @Fdebijl if you two are still interested, just respond back and I'll invite you

**Comment by peterpme** [comment]
Thank you **so** much!

**Comment by Fdebijl** [comment]
@peterpme Absolutely, sign me up

**Comment by peterpme** [comment]
Thanks so much @Fdebijl :)

I gave you "triage" access for now given your comment. If you end up needing more just message me :)

**Comment by peterpme** [comment]
I will close this ticket for now

**Comment by ciffelia** [comment]
@peterpme I'm still using this library and want to help too.

**Comment by peterpme** [comment]
@ciffelia you got i!

**Comment by ciffelia** [comment]
@peterpme Thanks!

**Comment by aditya** [comment]
@Fdebijl @ciffelia @peterpme any idea why the tests are broken?

**Comment by ciffelia** [comment]
@aditya 
- Twitter API keys on CI seems to be invalid.
- Tests in [twitter.test.js](https://github.com/draftbit/twitter-lite/blob/master/test/twitter.test.js) are working well on my local environment.
- [stream tests](https://github.com/draftbit/twitter-lite/blob/master/test/stream.test.js) seems to be broken. We might need to update `chattyUserIds`.
