### ISSUE TITLE
Could not authenticate you issue

### ISSUE THREAD

**Issue by jyothisjose** [draftbit/twitter-lite#160]
We are getting following error message 
**{"errors":[{"code":32,"message":"Could not authenticate you."}]}** 
on executing
**curl --request GET --url https://api.twitter.com/1.1/account_activity/webhooks.json --header 'authorization: Bearer AAAAAAAAAAAAAAAAAAAxxxxxxx'**

Can you please assist us to solve this issue?

**Comment by ciffelia** [comment]
Hi, jyothisjose.
twitter-lite is a Twitter API client for Node.js. Please visit https://twittercommunity.com/ to ask a question about using Twitter API on curl.
