### ISSUE TITLE
Two ways to access data?

### ISSUE THREAD

**Issue by pradeepb28** [draftbit/twitter-lite#182]
I've read the documentation and I just want to make myself more clear. There are two ways to retrieve data
- App + User token details (or)
- App only details.

In terms of sending http headers this is what needed?
App+ User request
- Consumer token & secret key
- User token & secret key
- Signature

App only requires header
- Bearer token

**Comment by ciffelia** [comment]
To make a request as a user you need:

- consumer token key and secret (per app)
- access token key and secret (per user)

This library will automatically generate required signatures and append them to the headers.

To make a request as an app you need:

- bearer token, which can be generated from consumer token key and secret

In this case no signatures are required. This library will automatically append them to the headers.
