### ISSUE TITLE
Should we rename this module? Twitter-lite is hard to search for

### ISSUE THREAD

**Issue by peterpme** [draftbit/twitter-lite#28]
Any suggestions for names?

**Comment by tylerbuchea** [comment]
Spit balling:

* twitter-api
* twitter-interface
* twitter-fetch
* awesome-twitter
* easy-twitter
* twitter-thin
* twitter-me
* @presposterous/twitter

Other words from here http://www.thesaurus.com/browse/light

**Comment by peterpme** [comment]
Awesome ideas, thanks!!

I tried googling "node twitter" and we def don't show up on the list. I know its going to take some time but with these new API changes I imagine we'll be able to grow our userbase!

**Comment by tylerbuchea** [comment]
Agreed, I landed on this lib because it was the only one I could find that was being maintained, had like no issues, and the code was clean/current. I think a lot of other people will find that appealing too. So thanks for your hard work.

We could call it `twitter-node` that would definitely cause a little confusion with the other library but it would be great for SEO. Also you could through in the org to make it more clear: @Preposterous/twitter-node

**Comment by peterpme** [comment]
I've reached out to the owner of twitter-node and hopefully he'll be open to the idea of donating the name! If not let's go with one of the ones you came up with cause they're awesome 😄

**Comment by tylerbuchea** [comment]
Sounds good, I opened a PR on his repo to deprecate his library in favor of this one. So hopefully one of our requests go through.

**Comment by peterpme** [comment]
Sorry I've been moving back from the west coast to the midwest the last couple of days! I can move everything over to the new name some time today :)

**Comment by tylerbuchea** [comment]
No rush, that is a big move! Hope it's going well.

**Comment by dandv** [comment]
@tylerbuchea: which repo might that be? Can't see a PR for thisat https://github.com/technoweenie/twitter-node/pulls

**Comment by tylerbuchea** [comment]
It's on this one https://github.com/desmondmorris/node-twitter/pull/284

node-twitter not twitter-node apologies if I confused the two.

Looks like the technoweenie one you link to is already deprecated in favor of https://github.com/AvianFlu/ntwitter which in turn is also deprecated.

The poor Node community this is a confusing mess.

Hopefully either @technoweenie/twitter-node or @desmondmorris/node-twitter are willing to give up their names.

**Comment by dandv** [comment]
`twi-lite`

**Comment by peterpme** [comment]
Do we still want `twitter-node`?

**Comment by peterpme** [comment]
We have the npm package? It's the reverse of node-twitter

**Comment by dylanirlbeck** [comment]
@peterpme Should we still change this to `twitter-node`?
