### ISSUE TITLE
image upload not working

### ISSUE THREAD

**Issue by Djiit** [draftbit/twitter-lite#29]
Hi there, 

I can't make this snipped work 

```js
const Twitter = require('twitter-lite')

var client = new Twitter({
  consumer_key: 'changed',
  consumer_secret: 'changed',
  access_token_key: 'changed',
  access_token_secret: 'changed'
})

var data = require('fs').readFileSync('./mymedia.png')

client.post('media/upload', { media: data })
  .then((err, media, res) => {
    console.log(err, media, res)
  })
```
The only thing i got is err = `{ errors: [ { message: 'Sorry, that page does not exist', code: 34 } ] }`

Did I miss something ? I'm on a macOS with nodejs v9 and the latest version of this lib.
Uploading the same image with twurl works like a charm.

Thanks

**Comment by Djiit** [comment]
Might be related to the fact that the media/upload endpoint is on the 'upload' subdomain, not the 'api' one.

**Comment by peterpme** [comment]
Hey @Djiit sorry for the delay. Were you able to figure this out?

**Comment by dandv** [comment]
@Djiit: it may be that `.post` needs a body parameter before the actual parameters. I've [documented that for the current version], but I think we should remove it altogether.

**Comment by dylanirlbeck** [comment]
Hey @Djiit, just checking in --- were you able to figure this out? We'd like to close this issue if so.

**Comment by Djiit** [comment]
No worries, I can't even remember what it was :-). I'm glad you are triaging all this, good luck !

**Comment by spongechameleon** [comment]
Hi y'all, just wondering what the status of posting to media/upload is? 

Although this issue along with #33 have been marked as closed, from my own fruitless attempts it seems that posting to media/upload is still unsupported by this library as I too receive `{ errors: [ { message: 'Sorry, that page does not exist', code: 34 } ] }`

Just want to make sure I'm not missing out on a working solution- I couldn't seem to find anything in the issues or the docs.

**Comment by linuxandchill** [comment]
worth reopening?

**Comment by peterpme** [comment]
@linuxandchill can ya fix it?

**Comment by Art3miX** [comment]
So basically you can't upload images? 

Not only the subdomain is different, headers should be also different

> Requests should be either multipart/form-data or application/x-www-form-urlencoded POST formats.

**Comment by Art3miX** [comment]
I know its not optimal, but to over come this I simply have 2 objects to handle the `api` and the `upload` subdomains. 

```
const TWApi     = new twitter({
    consumer_key:        TWITTER.API_KEY,
    consumer_secret:     TWITTER.SECRET,
    access_token_key:    result.token,
    access_token_secret: result.secret,
  }),
  uploadApi = new twitter({
    subdomain:           'upload',
    consumer_key:        TWITTER.API_KEY,
    consumer_secret:     TWITTER.SECRET,
    access_token_key:    result.token,
    access_token_secret: result.secret,
  });
```

It seems to be that the fix is simple, just to change the subdomain of of the request based on the resource given.

**Comment by insanity54** [comment]
There's a [good example of creating two clients in the test suite](https://github.com/draftbit/twitter-lite/blob/master/test/twitter.test.js#L17), while keeping it [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). One for api endpoint, one for upload endpoint. 

```js
function newClient(subdomain = 'api') {
  return new Twitter({
    subdomain,
    consumer_key: TWITTER_CONSUMER_KEY,
    consumer_secret: TWITTER_CONSUMER_SECRET,
    access_token_key: ACCESS_TOKEN,
    access_token_secret: ACCESS_TOKEN_SECRET,
  });
}
```

then you can do--

```js
const uploadClient = newClient('upload');
const apiClient = newClient();
```
