### ISSUE TITLE
POST Requests break when Twitter Returns no response

### ISSUE THREAD

**Issue by TheDeployGuy** [draftbit/twitter-lite#35]
Hey guys,

I was using the POST requests for many things and it was working perfectly but if the twitter api returns no body then request breaks. An example of a POST request that breaks it is: https://developer.twitter.com/en/docs/direct-messages/typing-indicator-and-read-receipts/api-reference/new-typing-indicator

Below is the error:
```
{ FetchError: invalid json response body at https://api.twitter.com/1.1/direct_messages/indicate_typing.json?recipient_id=50110518 reason: Unexpected end of JSON input
    at /Users/jasonlloyd/Documents/GitHub/MIDAS-API/node_modules/cross-fetch/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'FetchError',
  message: 'invalid json response body at https://api.twitter.com/1.1/direct_messages/indicate_typing.json?recipient_id=50110518 reason: Unexpected end of JSON input',
  type: 'invalid-json' }
```

I think its breaking at this line 66 in twitter.js ``` return response.json().then...```

I know you guys are just using node-fetch .json() to do get the json version for you but maybe it is something that needs to be looked at from the library side.

Please close if nothing you can do or you think it is not worth fixing.

Jason

**Comment by dandv** [comment]
Good catch! Fixed in e0abd741fa511f591b1ff6a66da98b2b1dd13863.
