### ISSUE TITLE
Statuses/update with error: 32 ‘could not authenticate you’ when ! or ' are in message

### ISSUE THREAD

**Issue by mniemiec92** [draftbit/twitter-lite#36]
Hi guys,

I’m trying to tweet a message, and in response I’m getting error 32 with ‘Could not authenticate you’ message. I found out that error is occure when I have in message ! or ' characters. 

I also found that someone has this error couple years ago - [https://twittercommunity.com/t/post-to-statuses-update-json-started-hitting-error-32-could-not-authenticate-you-with-no-code-changes/36495/9](url) but they posted that issue with twitter was fixed. 

I tried something like this  encodeURIComponent( inputStr ).replace( /[!'()*]/g, c => '%' + c.charCodeAt(0).toString(16) ); but message on twitter is with percent character and code, no parsing on twitter side.

Maybe someone have had the same problem as me or any idea how to make workaround?

**Comment by mniemiec92** [comment]
I wasn't. I changed npm module to 'twit' and it's working perfectly fine.

**Comment by rtwalz** [comment]
Thanks. Did the same and it works fine now.

**Comment by dandv** [comment]
Hey guys, sorry this took a while, but I've just pushed a fix and added a [comprehensive test](https://github.com/draftbit/twitter-lite/blob/d3cb8f236787a4f443b693e5a75a6db424388bd0/twitter.test.js#L180).

Enjoy v0.8!
