### ISSUE TITLE
URL encoded characters when creating a direct message

### ISSUE THREAD

**Issue by ericandrewlewis** [draftbit/twitter-lite#38]
Hey. This is my first post in this repository. Thank you for building and maintaining this library!

I'm sending a direct message like this:

```js
const messageParams = {
  event: {
    type: 'message_create',
    message_create: {
      target: {
        recipient_id: message.message_create.sender_id
      },
      message_data:  {
        text: `(away) ${randomGreeting()} - i am not on twitter for a bit - email me instead?`
      }
    }
  }
};
client.post('direct_messages/events/new', messageParams).then(response => {
  console.log(response);  // Raw response object.
  usersRepliedTo.add(message.message_create.sender_id);
});
```

and seeing content like this come through on the Twitter website:

<img width="340" alt="screen shot 2019-01-09 at 6 47 10 am" src="https://user-images.githubusercontent.com/1087646/50897543-6c29fc80-13da-11e9-98e4-52db6d7283bc.png">

Am I doing something wrong? Or is data getting URL encoded somewhere along the way that it shouldn't be?

**Comment by dandv** [comment]
Good catch, fixed and added a [test](https://github.com/draftbit/twitter-lite/blob/e10912c75fbe109f38c1cf442861be4af3b6551d/test/twitter.test.js#L149-L180)!
