### ISSUE TITLE
400 CORS Error when using library from the client

### ISSUE THREAD

**Issue by DanceParty** [draftbit/twitter-lite#41]
Maybe this is something on my end, but I am following the documentation and I have this code

```javascript
import Twitter from 'twitter-lite'

const client = new Twitter({
  subdomain: "api",
  consumer_key: process.env.CONSUMER_KEY, // from Twitter.
  consumer_secret: process.env.CONSUMER_SECRET, // from Twitter.
  access_token_key: process.env.ACCESS_TOKEN_KEY, // from your User (oauth_token)
  access_token_secret: process.env.ACCESS_TOKEN_SECRET // from your User (oauth_token_secret)
});

client
  .get("statuses/user_timeline.json?screen_name=twitterapi&count=2")
  .then(results => {
    console.log("results", results);
  })
  .catch(console.error);
```

but I am getting this response when running my code

`Failed to load resource: the server responded with a status of 400 ()`
```
Access to XMLHttpRequest at 'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=twitterapi&count=2.json' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
`TypeError: Network request failed at XMLHttpRequest.xhr.onerror`

However, I am able to successfully hit this end point with the same tokens in Postman. Any ideas! Hoping to get this working soon, thanks!

**Comment by dandv** [comment]
`twitter-lite` makes it easier to pass parameters than having to shove them into URLs :)

Check the [example for user_timeline](https://github.com/draftbit/twitter-lite/commit/37f2d92cca6537d62e422dadd53dbd4c1d66857a).

**Comment by KeevanDance** [comment]
Thank you for the quick reply, but the error still stands, I don't think it is related to how I am passing the variables in...?

![image](https://user-images.githubusercontent.com/10778294/51295119-bbc08780-19db-11e9-8ed0-424f43a75e1a.png)

![image](https://user-images.githubusercontent.com/10778294/51295126-c713b300-19db-11e9-88b6-8f29b5a35574.png)

**Comment by dandv** [comment]
We should create some tests for the client, @peterpme.

**Comment by KeevanDance** [comment]
Okay, didn't know if it was on my end. I can possibly look into contributing some tests this weekend!

**Comment by mbdilaver** [comment]
> Thank you for the quick reply, but the error still stands, I don't think it is related to how I am passing the variables in...?
> 
> ![image](https://user-images.githubusercontent.com/10778294/51295119-bbc08780-19db-11e9-8ed0-424f43a75e1a.png)

You have to use a CORS proxy (like `https://cors-anywhere.herokuapp.com/`). Change your subdomain like below. There are also other CORS services that you can use or you can setup your own. __Don't__ use these public proxy services for production.
After changing the subdomain like this, the CORS error no longer appears but I get `401` error for my `GET` and `POST` requests. I couldn't figure out what's the problem. At least you can give it a shot.
```
const client = new Twitter({
    subdomain: "cors-anywhere.herokuapp.com/https://api",
    consumer_key: X,
    consumer_secret: X,
    access_token_key: X,
    access_token_secret: X,
});
```

**Comment by KeevanDance** [comment]
@mbdilaver So maybe for production creating my own backend as a simple data pass through may be the best way for now?

**Comment by mbdilaver** [comment]
@KeevanDance Yeah that looks like the ideal solution. (https://developer.mozilla.org/tr/docs/Web/HTTP/CORS)

**Comment by KeevanDance** [comment]
@mbdilaver Thanks, I appreciate the quick response :)

**Comment by waleedshkt** [comment]
@DanceParty, Check out [this](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141) solution. 

The reason behind CORS error as I've recently found out is the absence of `Access-Control-Allow-Origin`  in the request header which browser doesn't send. This is actually a good requirement by twitter because it discourages the devs to use server-side as a security measure to prevent the leaking of twitter app api keys in the browser.

You can use the above solution for the development mode. But for production, if you are creating static site hosted on Netlify, Firebase, Heroku, for example, you can use their in-built proxy feature. This means then when making such twitter requests from your custom domain, it'll not encounter preflight CORS issue. 

Hope this slightly long comment helps out.

**Comment by MauriceOppenberger** [comment]
> > Thank you for the quick reply, but the error still stands, I don't think it is related to how I am passing the variables in...?
> > ![image](https://user-images.githubusercontent.com/10778294/51295119-bbc08780-19db-11e9-8ed0-424f43a75e1a.png)
> 
> You have to use a CORS proxy (like `https://cors-anywhere.herokuapp.com/`). Change your subdomain like below. There are also other CORS services that you can use or you can setup your own. **Don't** use these public proxy services for production.
> After changing the subdomain like this, the CORS error no longer appears but I get `401` error for my `GET` and `POST` requests. I couldn't figure out what's the problem. At least you can give it a shot.
> 
> ```
> const client = new Twitter({
>     subdomain: "cors-anywhere.herokuapp.com/https://api",
>     consumer_key: X,
>     consumer_secret: X,
>     access_token_key: X,
>     access_token_secret: X,
> });
> ```

any idea why 401 is getting returned?

**Comment by acailly** [comment]
I think I found the origin of the 401 error.

This lib delegate authentication header generation to `oauth-1.0a` dependency (https://github.com/ddo/oauth-1.0a) when it uses Twitter OAuth 1.0a authentication method (https://developer.twitter.com/en/docs/authentication/oauth-1-0a)

Authentication header should be computed with the endpoint URL without the proxy, but when you pass the subdomain containing the CORS proxy, it is used everywhere, event for this authentication header generation.

I found this workaround:

```javascript
  // In browser, use a CORS proxy
  // From https://github.com/draftbit/twitter-lite/issues/41#issuecomment-467403918
  const subdomain = isBrowser
    ? `${configuration.corsProxyURL.slice("https://".length)}https://api`
    : "api";

  const client = new Twitter({
    subdomain,
    version: "1.1",
    consumer_key: consumerKey,
    consumer_secret: consumerSecret,
    access_token_key: accessTokenKey,
    access_token_secret: accessTokenSecret,
  });

  // Monkey patch oauth client used by twitter-lite in order to
  // ignore cors proxy url when generating authentication headers
  const originalAuthorizeFunction = client.client.authorize;
  client.client.authorize = function (request, token) {
    let requestWihoutCorsProxy = request;
    if (request.url.startsWith(configuration.corsProxyURL)) {
      const requestUrlNotProxyfied = request.url.slice(
        configuration.corsProxyURL.length
      );
      requestWihoutCorsProxy = { ...request, url: requestUrlNotProxyfied };
    }
    return originalAuthorizeFunction.call(
      client.client,
      requestWihoutCorsProxy,
      token
    );
  };
```
