### ISSUE TITLE
Long running stream with 900+ follow ids

### ISSUE THREAD

**Issue by devkws** [draftbit/twitter-lite#42]
I have a stream running 24/7 following 900+ userids but several times a day this error is thrown, the stream seems to stay alive and does not need to be restarted, but i cannot seem to catch this error and handle it appropriately.

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
at Timer.processTimers (timers.js:223:10)
at listOnTimeout (timers.js:263:5)
at tryOnTimeout (timers.js:300:5)
at ontimeout (timers.js:436:11)
at TLSSocket.Socket._onTimeout (net.js:453:8)
at TLSSocket.emit (events.js:182:13)
at Object.onceWrapper (events.js:273:13)
at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
at ClientRequest.emit (events.js:182:13)
at Object.onceWrapper (events.js:273:13)
at ClientRequest.<anonymous> (/home/node/app/node_modules/request/request.js:816:19)
(node:1) UnhandledPromiseRejectionWarning: Error: ESOCKETTIMEDOUT

Also usually accompanied by:

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
(node:1) UnhandledPromiseRejectionWarning: Error: read ECONNRESET

**Comment by dandv** [comment]
What does your `stream.on('error', ...)` callback look like?

**Comment by devkws** [comment]
stream.on("error", error => console.log("error", error));


It’s a copy and paste from the documentation

**Comment by dandv** [comment]
I also have a long-running stream (on a reliable VPS) and have never seen this error in months, so it sounds like a connectivity problem. You could check in the error handler if the error is one of those two, and ignore it, since it's a temporary network error and as you said, the stream remains live.

**Comment by devkws** [comment]
Where should I be checking for this? In the stream on error? I ran in debug with a breakpoint on the log and it doesn’t seem to be thrown from there. It look like it’s thrown somewhere deeper maybe? I even added a “thrown from on error” log and it’s never written.

**Comment by devkws** [comment]
added the following code to essentially ignore the error.
``` 
process.on('unhandledRejection', (reason, p) => {
    //console.log(('Unhandled Rejection at: Promise' + p + 'reason:' + reason));
  });

```
