### ISSUE TITLE
1.0 breaking changes

### ISSUE THREAD

**Issue by dandv** [draftbit/twitter-lite#44]
List of breaking changes to ponder for v1.0:

* [ ] change the `._headers` format from a plain hash to the [Header](https://developer.mozilla.org/en-US/docs/Web/API/Headers) object. More difficult to manipulate, but "standard". Currently, we're using node-fetch's [.raw() internal workaround](https://github.com/bitinn/node-fetch/issues/156#issuecomment-242628473).

**Comment by waleedshkt** [comment]
Please check https://github.com/draftbit/twitter-lite/issues/52#issue-478161610

**Comment by dylanirlbeck** [comment]
@dandv Can you revisit this issue and clarify what we need before publishing a v1.0?
