### ISSUE TITLE
v0.9.3 not working

### ISSUE THREAD

**Issue by CannibalKush** [draftbit/twitter-lite#45]
Version 0.9.3 seems to be missing a dist folder after I npm install it. Had to downgrade back to 0.9.1

**Comment by Fallenstedt** [comment]
I believe this has been closed with: https://github.com/draftbit/twitter-lite/commit/77562f382a6985ba3ae209e97ba199bb67de6e5b

**Comment by dandv** [comment]
Correct, thanks @Fallenstedt.
