### ISSUE TITLE
How to handle rate limiting with multiple apps

### ISSUE THREAD

**Issue by KayHS** [draftbit/twitter-lite#47]
Hi,

I need to fetch large amounts of data. I am fetching tweets from every follower of a specific user, the user has over 1 million followers.

I have multiple twitter apps is it possible to handle rate limiting by using these multiple api tokens. For example when one is about to reach the limit to exchange the next request to use the next api token.

Is there an example of this?

**Comment by tylerbuchea** [comment]
I think your use case might go against the Twitter API agreement, so you might want to check that. I think you can pay for increased API limits https://developer.twitter.com/en/pricing.html which may solve your problem.

Although your use case isn't something we plan on adding support or documentation for I think it technically could be done by creating multiple clients with different API keys and manually keeping track of each clients rate limits and then switching when needed.

```js
const clients = {
  [ client: new Twitter(credentials1), requestsLeft: null ],
  [ client: new Twitter(credentials2), requestsLeft: null ],
};

function doTheThing() {
  // run some function that queries for and updates each clients requestsLeft
  // determine how many queries needed for next query
  // loop through clients to find a client with enough requestsLeft
  // if client found exectue next query using selected client
} 

setInterval(doTheThing, 5000);
```

**Comment by dylanirlbeck** [comment]
@KayHS I think Tyler gave a really good answer, so I'm going to close this issue out.

**Comment by Nisthar** [comment]
@dylanirlbeck @tylerbuchea You need to apply for `bearer_token` when changing the clients. Right?
