### ISSUE TITLE
Calling stream.destroy() does not emit any events

### ISSUE THREAD

**Issue by roowilliams** [draftbit/twitter-lite#48]
Hello,

I'm currently running a 24/7 stream on a server that occasionally needs to be stopped and started again programmatically to change track params.

When developing locally and stopping/restarting the server via the command line, it seems pretty resilient to 420 errors. When using `stream.destroy()`, waiting 20-30 seconds and restarting the stream I get 420 errors on the 1st or 2nd try - it seems very sensitive.

Despite listening to 'error' and 'end' events (which work at other times) I am not getting any events after `stream.destroy()` is called, even if deferred and I have a feeling this may be causing the 420 errors as the stream isn't being stopped properly.

Does this still ring true?
```
// To stop the stream:
process.nextTick(() => stream.destroy());  // emits "end" and "error" events
```

**Comment by danstronoid** [comment]
I'm running into the same problem.  When I use `stream.destroy()` and wait 30 seconds to reconnect I seem to get an error 420 on the third connection without fail, but if I stop and restart the stream from the command line, it seems to work just fine.

**Comment by ImTheDeveloper** [comment]
Anyone get further with this?

**Comment by dylanirlbeck** [comment]
@roowilliams @danstronoid @ImTheDeveloper So this may not be the reason, but have you both looked at https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/connecting? In the `Reconnecting` section, the docs state that after receiving HTTP 420 errors you should do the following:

```
Back off exponentially for HTTP 420 errors. Start with a 1 minute wait and double each attempt. Note that every HTTP 420 received increases the time you must wait until rate limiting will no longer will be in effect for your account.
```

The first thing I would try and do is follow their recommendation for backing off exponentially. Please let me know if this helps!

**Comment by dylanirlbeck** [comment]
I'm going to close this issue for now. If anyone is still experiencing it, please feel free to reach out and I'll re-open.

**Comment by karthik947** [comment]
I'm facing this issue again, has anyone found the solution ?
