### ISSUE TITLE
No media entities on an image tweet

### ISSUE THREAD

**Issue by atomheartother** [draftbit/twitter-lite#49]
Hello,

Whether I use the Streaming API or the `statuses/user_timeline` endpont, there are certain tweets where I simply won't get any image data from the API, when there clearly is an image in the tweet.

This was reported by an user of mine, who got 0 images when getting tweets from this account: https://twitter.com/AzurLane_EN

When I get this user's timeline, images that I can clearly see on twitter are not visible in the `tweet` object that's returned. Not only are there no `extended_entities`, there isn't a single trace of the linked image in the entire object.

Has anyone here ever encountered this? Twitter's documentation seems to state pretty clearly that wherever there is an image, there is an `extended_entities` object...

**Comment by dandv** [comment]
The library doesn't do anything special with entities, or extended tweets. It simply [parses the JSON returned by Twitter](https://github.com/draftbit/twitter-lite/blob/77562f382a6985ba3ae209e97ba199bb67de6e5b/twitter.js#L207-L219).

This sounds like an issue with the Twitter API itself. Can you perhaps post in the [Twittercommunity forum](https://twittercommunity.com/search?q=entities) and see if others have run into this?

Something else to try is figure out exactly which tweets lack the entities, and as a sanity check, see what `twurl` or [Twitsandbox](https://twitsandbox.com/?lang=en) return for them.

**Comment by atomheartother** [comment]
Yeah that's what I'll do I just wanted to check if it was a known bug with you guys before bringing it to the twitter guys. Closing this as it's been confirmed it's probably not the library.

**Comment by atomheartother** [comment]
The cause was that I needed to use `tweet_mode: "extended"` in my params. It now appears to work flawlessly.
