### ISSUE TITLE
Support other Twitter APIs

### ISSUE THREAD

**Issue by AmichayMiara** [draftbit/twitter-lite#50]
Hey twitter-lite,
Really enjoy to work with yours twitter **Promise** library! Thanks a lot.

Twitter had more APIs,
 that I think that you can support with only little changes in the `subdomain, endpoint` section.
Maybe can be manege through GET params.

For example:
ads-api.twitter.com/5/stats/accounts
subdomain = 'ads-api'
endpoint = '5'

data-api.twitter.com/insights/engagement/totals
subdomain = 'data-api'
endpoint = ''

**Twitter Ads API**
https://developer.twitter.com/en/docs/ads/general/guides/getting-started

**Engagement API**
https://developer.twitter.com/en/docs/metrics/get-tweet-engagement/api-reference/post-insights-engagement

Can you support it?

**Comment by dylanirlbeck** [comment]
Closing this issue because we know have #62 to track support for other Twitter APIs.
