### ISSUE TITLE
"Null" Consumer_Key in Authorization Header

### ISSUE THREAD

**Issue by waleedshkt** [draftbit/twitter-lite#52]
Running a simple GET request to verify credentials gave the following error in twitter.m.js

> e.headers.raw() is not a function

To debug it, I removed it from `h._handleResponse` function. The above error went away but received  a response from twitter server of `401`.

On looking the request, I found `OAuth oauth_consumer_key="null"` in `Authorization` header.

Seems like the function is not setting the auth header correctly?

**Comment by KiraNavarro** [comment]
I'm also getting the same error 

`TypeError: e.headers.raw is not a function
    at h._handleResponse`

Have you found a work around to this?

**Comment by dylanirlbeck** [comment]
@waleedshkt @KiraNavarro First of all, are you both still having this issue? If so, can you please post your code snippets so I can try and reproduce? Thanks in advance!

**Comment by matt2legit** [comment]
I'm seeing this in my react-native application.  I removed the `.raw()` and it works fine.  Using [patch-package](https://github.com/ds300/patch-package) for now to save this change in my project.

**Comment by Nick-Gottschlich** [comment]
I am also having this issue. I am running twitter-lite inside of a vue-electron app:

```javascript
  handleTwitterLogin = () => {
    const client = new Twitter({
      consumer_key: twitterApi.consumer_key,
      consumer_secret: twitterApi.consumer_secret
    });

    const { BrowserWindow } = electron.remote;
    let twitterApiWindow;
    let oauth_verifier;
    let userClient;

    client
      .getRequestToken("https://google.com")
      .then(res => {
        console.log({
          reqTkn: res.oauth_token,
          reqTknSecret: res.oauth_token_secret
        });

        twitterApiWindow = new BrowserWindow({});
        twitterApiWindow.loadURL(
          `https://api.twitter.com/oauth/authenticate?oauth_token=${res.oauth_token}`
        );
        twitterApiWindow.webContents.on("did-navigate", (event, url) => {
          if (url.indexOf("google") >= 0) {
            const searchParams = new URLSearchParams(url.slice(23));
            oauth_verifier = searchParams.get("oauth_verifier");

            client
              .getAccessToken({
                key: res.oauth_token,
                secret: res.oauth_token_secret,
                verifier: oauth_verifier
              })
              .then(response => {
                console.log({
                  accTkn: response.oauth_token,
                  accTknSecret: response.oauth_token_secret,
                  userId: response.user_id,
                  screenName: response.screen_name
                });

                userClient = new Twitter({
                  consumer_key: twitterApi.consumer_key,
                  consumer_secret: twitterApi.consumer_secret,
                  access_token_key: response.oauth_token,
                  access_token_secret: response.oauth_token_secret
                });

                userClient.get('statuses/user_timeline', {
                  user_id: response.user_id
                }).then((userTweets) => {
                  console.log('userTweets', userTweets)
                })
              })
              .catch(console.error);
          }
        });
      })
      .catch(console.error);
  };
```

I've tried removing the .raw and using patch-package but I still seem to be getting the same error.

**Comment by peterpme** [comment]
Hey @Nick-Gottschlich and @matt2legit do you mind opening up a PR to fix this issue in the lib if its not already?

Otherwise we can close out this issue. Thanks!

**Comment by Nick-Gottschlich** [comment]
@peterpme I got you fam, always wanted to be one of dem open-source contributors™️ 👌

**Comment by peterpme** [comment]
Thanks @Nick-Gottschlich !! Release in 0.11.0 :smile:
