### ISSUE TITLE
TypeError: stream.destroy is not a function

### ISSUE THREAD

**Issue by KNCal** [draftbit/twitter-lite#54]
I am using this code:

const client = new Twitter({
  consumer_key: "xyz" // from Twitter.
  consumer_secret: "xyz" // from Twitter.
  access_token_key: "abc" // from your User (oauth_token)
  access_token_secret: "abc" // from your User (oauth_token_secret)
});

const parameters = {
  track: "#bitcoin,#litecoin,#monero",
  follow: "422297024,873788249839370240",  // @OrchardAI, @tylerbuchea
  locations: "-122.75,36.8,-121.75,37.8",  // Bounding box -	San Francisco
};

const stream = client.stream("statuses/filter", parameters)
  .on("start", response => console.log("start"))
  .on("data", tweet => console.log("data", tweet.text))
  .on("ping", () => console.log("ping"))
  .on("error", error => console.log("error", error))
  .on("end", response => console.log("end"));

// To stop the stream:
process.nextTick(() => stream.destroy());  // emits "end" and "error" events

and get the following error:

process.nextTick(() => stream.destroy());
                              ^

TypeError: stream.destroy is not a function

**Comment by dandv** [comment]
Looks like your `stream` isn't initialized yet. See how destroying works in [the test suite](https://github.com/draftbit/twitter-lite/blob/77562f382a6985ba3ae209e97ba199bb67de6e5b/test/stream.test.js#L74).

Also, please format your code using triple backticks :)

**Comment by KNCal** [comment]
Ah ok. Thank you! :)
