### ISSUE TITLE
Support for new twitter Premium Search and LABS API

### ISSUE THREAD

**Issue by pantchox** [draftbit/twitter-lite#55]
This lib looks promising, I did not use it yet but it seems maintained comparing to the "Twit" one.

There are few new endpoints available for premium sandbox users (anyone can apply if they already have a dev account on Twitter)
https://developer.twitter.com/en/docs/tweets/search/overview/premium

and also the new "Fitered Stream" which will replace the current "status/filter" endpoint
https://developer.twitter.com/en/docs/labs/filtered-stream/overview

thanks

**Comment by dylanirlbeck** [comment]
I see the support for Filtered Stream as totally valid request, but I'm not completely sure how our library wouldn't support some of the new endpoints for premium sandbox users.

In any event, I'm going to close this issue because we now have #62 for tracking support for other Twitter APIs.
