### ISSUE TITLE
Square brackets misinterpreted in post params?

### ISSUE THREAD

**Issue by trey-k** [draftbit/twitter-lite#58]
I have something set up like below but no matter what you do I get an unhandled error that says nothing specific about an #<Object>. If you remove the brackets from the string it works fine, escaping them doesn't seem to help, any ideas?
```javascript
const params = {
  name: '[🔴 LIVE] name',
  description: 'new bio'
}

client.post('account/update_profile', params) {
  .then(function (data) {
    //do whatever
  })
  .catch(function (error) {
    throw error
  })
```

**Comment by dylanirlbeck** [comment]
HI @trey-k, thanks for reporting this issue. It looks like Twitter usernames can only contains letters, numbers, and '_' (I just tried manually changing my own Twitter username and was unable to include brackets). 

I'm going to close this issue for now, but please feel free to re-open if you have other problems.
