### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by WesSouza** [draftbit/twitter-lite#61]
Is there an interest in supporting TypeScript, either by switching the source or adding type definition files?

If so I'd be happy to help :)

Thanks for the library, btw.

**Comment by dylanirlbeck** [comment]
Hi @WesSouza, thanks for reaching out! TypeScript support would be awesome. Feel free to open a PR if you're able! In the meantime, I'll flag this as a new feature and we can get to it if we have time.
