### ISSUE TITLE
Endpoint "media/metadata/create" fails

### ISSUE THREAD

**Issue by NiciusB** [draftbit/twitter-lite#67]
The endpoint `https://upload.twitter.com/1.1/media/metadata/create.json` fails due to content being sent in `application/x-www-form-urlencoded`, but it only accepts `application/json`
I tried adding it to `JSON_ENDPOINTS` but it fails with an invalid json response.

Code sample:
```es6
const twUploadClient = new Twitter({
  subdomain: 'upload',
  consumer_key: credentialsArray[0],
  consumer_secret: credentialsArray[1],
  access_token_key: credentialsArray[2],
  access_token_secret: credentialsArray[3]
})

// Upload image
const mediaUploadData = await twUploadClient.post('media/upload', { media_data: b64content })

// Set alt text for image
if (card.alt && card.alt.length > 0) {
  await twUploadClient.post('media/metadata/create', { media_id: mediaUploadData.media_id_string, alt_text: { text: imageAltString } })
}
```

Doc page for `media/metadata/create` for reference: https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-metadata-create

**Comment by NiciusB** [comment]
It seems like it actually makes a successful request, but it fails to parse the result.

Here is some extremely hacky code if anyone needs it. It's bad, but it will not throw
```
const crossFetch = require('cross-fetch')

function customTwitterPostForAltText (twitterClient, body) {
  const resource = 'media/metadata/create'
  const baseHeaders = {
    'Content-Type': 'application/json',
    Accept: 'application/json'
  }

  const { requestData, headers } = twitterClient._makeRequest(
    'POST',
    resource,
    null // don't sign JSON bodies; only parameters
  )

  const postHeaders = Object.assign({}, baseHeaders, headers)
  body = JSON.stringify(body)

  return crossFetch(requestData.url, {
    method: 'POST',
    headers: postHeaders,
    body
  })
    .then(res => {
      if (res.status !== 200) throw new Error('[customTwitterPostForAltText] ' + JSON.stringify(res))
    })
}
```

**Comment by dylanirlbeck** [comment]
Hi @NiciusB, sorry for the delay. I'm a bit confused, did you solve this issue with the snippet you posted above?

**Comment by NiciusB** [comment]
I did, but it's not ideal since it's ignoring the result of the request. If the network fails, the request will throw. But if twitter returns an error, I'm not sure if it will fail or not
Basically what I wanted to do was to upload an image with a caption.

```
// Upload image
const b64content = '' // Base64-encoded image
const mediaUploadData = await twUploadClient.post('media/upload', { media_data: b64content })

// Set alt text for image
const altTextString = 'Animated image of a cat failing a jump'
await customTwitterPostForAltText(twUploadClient, { media_id: mediaUploadData.media_id_string, alt_text: { text: altTextString } })

// Tweet
const tweetData = await twClient.post('statuses/update', {
  status: 'Check out my accesible image',
  media_ids: [mediaUploadData.media_id_string]
})
```
For reference this is the original file: https://github.com/NiciusB/valentine-cards-bot/blob/master/src/cron/sendTweet.js

**Comment by peterpme** [comment]
Hey @NiciusB do you mind creating a PR that would fix this for our users? We'd really appreciate it, thanks!
