### ISSUE TITLE
Get full posts

### ISSUE THREAD

**Issue by oavkdtv** [draftbit/twitter-lite#68]
Question: Is there a way to prevent a tweet getting a link attached when using the stream API? E.g:
`got data Der heutige Stream wird wie üblich sabotiert von aodefpne_ewroieüsmserv liefert instabilen Upload wie in 2013, läs… https://t.co/wDNa1p07k0`
I don't want the link a the end, I'd rather like to get the full tweet.

**Comment by oavkdtv** [comment]
... found it: data.extended_tweet.full_text :-)

**Comment by andrewc2** [comment]
Could you perhaps expand a bit on how you used it? I'm trying to figure that out currently and am at a loss.
