### ISSUE TITLE
Support for Twitter Developer Labs / next version endpoints

### ISSUE THREAD

**Issue by andypiper** [draftbit/twitter-lite#69]
Hello from Twitter Developer Relations!

First of all: Thank You, for building on our API, and for supporting our developer communities! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around!

We're currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs to twitter-lite! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

As we hope you know, we do list twitter-lite on our developer libraries page https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries and we would really love to continue to do so as you continue to help the Javascript community. Thank you all, again!

**Comment by peterpme** [comment]
Hey @andypiper, sure would love to chat. Let me know how we can help!

**Comment by andypiper** [comment]
Thanks Peter, I'll follow-up! In the meantime, check out our new support for annotations in v2 of Labs! https://twittercommunity.com/t/adding-annotations-to-tweets-and-recent-search-endpoints-in-labs/135193

**Comment by peterpme** [comment]
Hey @andypiper just a friendly ping! If you're able to create tickets for some of the new features I'm sure our users would be down to help implement :smile:
