### ISSUE TITLE
Tweet thread

### ISSUE THREAD

**Issue by Shreerang** [draftbit/twitter-lite#71]
Can someone add an example for posting a thread of tweets using this library?

**Comment by NiciusB** [comment]
You just need to send a normal tweet, but add the last tweet's id in `in_response_to`.
I haven't tested the following code but it should work.

```
const thread = ['First tweet', 'Second tweet', 'Third tweet']
let lastTweetID
for (const status of thread){
  const tweet = await client
    .post("statuses/update", {
      status: status,
      in_reply_to_status_id: lastTweetID,
      auto_populate_reply_metadata: true
    })
  lastTweetID = tweet.id_str
}
```

**Comment by dylanirlbeck** [comment]
Thanks @NiciusB! @Shreerang let us know if you need any more help.

**Comment by peterpme** [comment]
@NiciusB would you mind adding this to the README? Thank you!
