### ISSUE TITLE
getAccessToken outdated and unusable

### ISSUE THREAD

**Issue by T0TProduction** [draftbit/twitter-lite#78]
As can be seen [here](https://github.com/draftbit/twitter-lite/blob/master/twitter.js#L148) the current function only adds `oauth_verifier`. According to the [docs](https://developer.twitter.com/en/docs/basics/authentication/api-reference/access_token), `oauth_token` is also required.
Using this function returns- as expected - this:
`[Object: null prototype] { 'Request token missing': '' }`

**Comment by peterpme** [comment]
Hey @T0TProduction thank you for reporting this! Can you please open a PR?
