### ISSUE TITLE
TypeError: "not a constructor" when using TypeScript

### ISSUE THREAD

**Issue by danbockapps** [draftbit/twitter-lite#83]
I get this error when using the example code at the top of index.d.ts:

```
Users-MacBook-Pro:twitter-lite-test danbock$ ts-node dev.ts 

/Users/danbock/code/twitter-lite-test/dev.ts:3
const twitter = new Twitter({
                ^
TypeError: twitter_lite_1.Twitter is not a constructor
    at Object.<anonymous> (/Users/danbock/code/twitter-lite-test/dev.ts:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (/Users/danbock/.nvm/versions/node/v12.16.2/lib/node_modules/ts-node/src/index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/danbock/.nvm/versions/node/v12.16.2/lib/node_modules/ts-node/src/index.ts:839:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at main (/Users/danbock/.nvm/versions/node/v12.16.2/lib/node_modules/ts-node/src/bin.ts:226:14)
    at Object.<anonymous> (/Users/danbock/.nvm/versions/node/v12.16.2/lib/node_modules/ts-node/src/bin.ts:485:3)
```

I reproduced this on a blank project. Just ran `npm install twitter-lite` and copied this code into a blank file and ran it using ts-node. Got the same error.

```
import { Twitter } from 'twitter-lite';

const twitter = new Twitter({
 consumer_key: 'XYZ',
 consumer_secret: 'XYZ',
 access_token_key: 'XYZ',
 access_token_secret: 'XYZ'
});
```

**Comment by AlberErre** [comment]
Same issue here 🤷🏻‍♂️

I've added `// @ts-ignore` above that line as a temporary workaround.

**Comment by danbockapps** [comment]
@AlberErre Above what line? I believe that TypeScript compilation is actually happening without errors, and the TypeError I'm seeing is a runtime JavaScript error.

**Comment by kyleratti** [comment]
@danbockapps I am seeing the same thing on `typescript@^3.8.3` and `twitter-lite@^0.10.1-0`. I think this has to do with the [typings exporting the entire namespace](https://github.com/draftbit/twitter-lite/blob/23cf5bc1c169c14baffb61f8a7a1e39915fb6328/index.d.ts#L147) while the actual library [exports the Twitter class](https://github.com/draftbit/twitter-lite/blob/23cf5bc1c169c14baffb61f8a7a1e39915fb6328/twitter.js#L356).

I was a bit confused by the suggestion from @AlberErre as well, but I realized he meant he added `// @ts-ignore` above the client line like so:

```ts
import Twitter from "twitter-lite"; // typings and runtime OK for this line

...

// changing your import to match above will trigger 'This expression is not constructable.'
// the @ts-ignore flag will let TS compile anyway
// @ts-ignore
const twitter = new Twitter({
 consumer_key: 'XYZ',
 consumer_secret: 'XYZ',
 access_token_key: 'XYZ',
 access_token_secret: 'XYZ'
});
```

**Comment by danbockapps** [comment]
To be clear, there are **two** necessary changes from the sample code in the comment at the top of index.d.ts:

1. Remove the curly brackets from the import statement
2. Add `// @ts-ignore` above the call to create a `new Twitter`

In my blank project I also had to add `"esModuleInterop": true` to the `compilerOptions` in tsconfig.json. Then the code ran.

**Comment by dylanirlbeck** [comment]
Hi all, sorry you're seeing these errors in TypeScript. We just added typings to the library, so there was bound to be some bugs 😄 That said, I'd encourage all of you to take a look to see if you can find the issue and open a PR!

I'm going to cc @Fdebijl since he made the PR for types originally. I'm no TS expert so hopefully we can work together to get this fixed before the next release of `twitter-lite`.

**Comment by Fdebijl** [comment]
I completely overlooked `esModuleInterop` while developing the typings, I'm submitting a PR with a fix as we speak.

Following this PR, the safe import signature (which will work without `esModuleInterop`) is `import Twitter = require('twitter-lite');`, but if `esModuleInterop` is enabled `import Twitter from 'twitter-lite';` will also work. 

Note that the `import ... require` signature doesn't allow you to import typings from twitter-lite, so I would recommend using `esModuleInterop` in any event.

**Comment by DalderupMaurice** [comment]
I've had this issue with version `1.1.0`
Had to add `esModuleInterop: true` to fix the issue, without it gives the error
