### ISSUE TITLE
pre-commit hook broken

### ISSUE THREAD

**Issue by T0TProduction** [draftbit/twitter-lite#90]
just created a new PR, and when trying to push to my branch the commit hook denied me.
I temporarily deactivated to be able to commit, but I'm not sure what exactly went wrong.

To me, it looks like it's looking for eslint at the wrong place.
I have it installed locally as well as globally.
Inside my IDE as well as normally over the command line, eslint works just as expected.

![image](https://user-images.githubusercontent.com/18548570/80710303-dfcfab80-8aee-11ea-8735-e968aec9131d.png)

**Comment by peterpme** [comment]
Hey @T0TProduction, I tried this locally and it seemed to work. If this is still an issue, please re-open and let us know. Thanks!
