### ISSUE TITLE
Old version of index.d.ts is included in dist (new version is in root)

### ISSUE THREAD

**Issue by danbockapps** [draftbit/twitter-lite#93]
When I `npm install twitter-lite` and then look in node_modules/twitter-lite, I see two versions of `index.d.ts`: the current one, in the twitter-lite folder, and an old version, in twitter-lite/dist.

The old one doesn't seem to be causing any problems on my machine (TypeScript is referring to the one in the root folder), but we probably don't want old unused code hanging around.

**Comment by peterpme** [comment]
recently published 0.12.0, give that a shot. Thanks!
