### ISSUE TITLE
Rate limit headers not attached to error object

### ISSUE THREAD

**Issue by kmaid** [draftbit/twitter-lite#94]
I am finding when i hit the twitter "friends/ids" endpoint 16 times the expected `{ errors: [ { message: 'Rate limit exceeded', code: 88 } ]` is thrown but does not contain _headers.

I am hoping to use e._headers["x-rate-limit-reset"] to tell me when to continue my job as indicated in the documentation. (https://github.com/draftbit/twitter-lite/blob/master/README.md#api-errors)

I think it was broken in this merge:
https://github.com/draftbit/twitter-lite/pull/75/files

By this line not throwing the json object & headers
https://github.com/draftbit/twitter-lite/blob/b19263b1ce5afd7617583672575d317ad31acfc8/twitter.js#L100

If I can get your tests to run ill raise a PR and write a test.

Can i introduce Nock rather than actually hitting the twitter API to simulate these conditions?

**Comment by kmaid** [comment]
https://github.com/draftbit/twitter-lite/pull/95

Not sure how you link issues. It usually happens automatically in jira ^^;

**Comment by paulmars** [comment]
getting this too

**Comment by paulmars** [comment]
0.9.4 appears to work so far

**Comment by peterpme** [comment]
0.12.0 was just published, please give that a shot!

**Comment by kmaid** [comment]
This has resolved my issue. Thanks
